# These are supported funding model platforms

github: LISA-KOREA # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
buy_me_a_coffee: lisakorean # Replace with a single Buy Me a Coffee username
custom: https://graph.org/file/5adb7b1b3735ab3b53ca9.jpg # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']

